### PR TITLE
Merged thoughtbot again to get my application tests to pass on Rails 3.0 final

### PR DESCRIPTION
**Pull request by pwnall**
Dear Pat,

I've been using your code successfully for some time, then I upgraded to the final Rails 3.0.0 release, and my tests broke. I merged thoughtbot's changes, and my tests work again. There are 2 broken tests in paperclip, but my app doesn't seem to hit them, so I didn't fix them (it's 6am and I'd like to sleep).

I noticed that thoughtbot factored out their storage engines. I hope this means it'll be easier for you to maintain your fork.

Once again, thank you for your great work!
    Victor

### CODE REVIEW

**Comment by patshaughnessy** [comment]
Hi there - someone else asked about merging up to Thoughtbot so I'll try to get to this soon. Note: I did merge with the master repo back in April. Not sure if you were using that version, or something older.

**Comment by pwnall** [comment]
Hi, Pat!

I tried the latest in your Rails 3 branch before messing with the code. I get lazy at late hours, so I would've definitely stuck with your code if I could've gotten away with that :)

On the bright side, the merge seemed pretty straight-forward, so I hope you won't have too much trouble when you get around to it!

**Comment by patshaughnessy** [comment]
Hi again Victor,

FYI I just finished the merge now and pushed to github. I removed the "rails3" branch and you can just use my master branch. I ended up with almost exactly the same code you sent me, except for a couple of minor bug fixes... maybe related to your failing unit tests in paperclip.

Anyway thanks for pushing me to do this again, and let me know if you run into any trouble with the new code. I'll try to merge from Thoughtbot more frequently so this isn't so hard to do in the future. cheers, - pat

**Comment by pwnall** [comment]
Thank you so much, Pat! The code works great, except for a minor glitch when trying to load it as a gem. I sent you a pull request.

Once again, thank you for being so responsive, and for the awesome code!

**Pull request closed without merging**
